### ISSUE TITLE
hyperopt error

### ISSUE THREAD

**Issue by Daniel595** [mkajnar/HighProfitStrategy#3]
Hey @mkajnar,
thanks for sharing your strategie. I really enjoy it so far :-) 

Im wondering if you're Hyperopting your Strategies inheriting from `HPStrategy`? I tried to hyperopt as I do usually using:
```bash
freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --spaces roi stoploss trailing buy sell --strategy HPStrategyTFJPA --config /freqtrade/user_data/configs/hp_config.json --config /freqtrade/user_data/configs/static_pairlist.json --config /freqtrade/user_data/configs/whitelist_50.json -e 500 --timerange=20230101- 
```

I get an error:

```bash
2023-12-28 22:03:48,288 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 106, in start_hyperopt
    hyperopt = Hyperopt(config)
               ^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 98, in __init__
    self.hyperopt_pickle_magic(self.backtesting.strategy.__class__.__bases__)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 156, in hyperopt_pickle_magic
    cloudpickle.register_pickle_by_value(sys.modules[modules.__module__])
                                         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'HPStrategy'
```

Did you ever faced this problem?
Im using docker `freqtrade:stable`.

Also I'd be really interested in some hyperopt results if you're willing to publish them :-)

Thank you very much

**Comment by Daniel595** [comment]
With some advices from the freqtrade discord channel I solved the problem by flattening the classes. Suddenly hyprtopting works. I also got the Hint that hyperopting of derived classes will drop the hyperopt params from the base classes.

May I ask for your practice of hyperopting? 
Thanks again :-)

**Comment by mkajnar** [comment]
Try this  - it is flattened and working better than HPStrategy* childs . Of course it is hyperoptable... https://raw.githubusercontent.com/mkajnar/HighProfitStrategy/main/user_data/strategies/HPStrategyTFJPAConfirmV1.py

**Comment by mkajnar** [comment]
Best results on 5 m timeframe

**Comment by mkajnar** [comment]
We can cooperate together for better results. :)

**Comment by Mcm5s** [comment]
> Try this - it is flattened and working better than HPStrategy* childs . Of course it is hyperoptable... https://raw.githubusercontent.com/mkajnar/HighProfitStrategy/main/user_data/strategies/HPStrategyTFJPAConfirmV1.py

Hey i'm tying this one but i got an error:
2023-12-30 22:53:46 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error input_arrays parameter missing required data key: close calling <bound method IStrategy._analyze_ticker_internal of <HPStrategyTFJPAConfirmV1.HPStrategyTFJPAConfirmV1 object at 0x7fc47bd4b9a0>>
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 873, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 851, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 1378, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/root/freqtrade/user_data/strategies/HPStrategyTFJPAConfirmV1.py", line 302, in populate_indicators
    btc_info_tf = self.info_tf_btc_indicators(btc_info_tf)
  File "/root/freqtrade/user_data/strategies/HPStrategyTFJPAConfirmV1.py", line 654, in info_tf_btc_indicators
    dataframe['rsi_8'] = ta.RSI(dataframe, timeperiod=8)
  File "talib/_abstract.pxi", line 444, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 303, in talib._ta_lib.Function.set_function_args
  File "talib/_abstract.pxi", line 251, in talib._ta_lib.Function.set_input_arrays
Exception: input_arrays parameter missing required data key: close

**Comment by Mcm5s** [comment]
^^ Update
Fixed it, currency issue.

Maybe its an idea to make a discord?

**Comment by mkajnar** [comment]
Take new version HPStrategyTFJPAConfirmV1 - added combinations for more signals

**Comment by mkajnar** [comment]
> Iam gonna dry run HPStrategyTFJPAConfirmV1.
> 
> Maybe its an idea to make a **discord**?

https://discord.gg/DRHuuHtD

**Comment by mkajnar** [comment]
Done
